### ISSUE TITLE
Unknown variable 'reducer.mean.exclude'

### ISSUE THREAD

**Issue by lilstipher** [senx/warp10-ext-flows#2]
Hi,
I'm facing a problem when trying to use `reducer.mean.exclude-nulls( )` flows function. 
When I'm trying to use reduce ex: (`REDUCE([ data_bucketized, [], reducer.mean.exclude-nulls() ])`), the server returns:  __Unknown variable 'reducer.mean.exclude'__. 
Have you already experienced this problem ?
Thanks

**Comment by hbs** [comment]
Hi,

some functions cannot be called directly due to their name interfering with the supported FLoWS syntax. In the present case the presence of '-' in the name is interpreted as a subtraction in FLoWS. In order to circumvent this type of issue you can replace `reducer.mean.exclude-nulls()` by `EVAL('reducer.mean.exclude-nulls')`

**Comment by lilstipher** [comment]
Thanks,
the documentation is just a bit confusing, ex : [reducer.mean.exclude-nulls()](https://www.warp10.io/doc/reducer.mean.exclude-nulls). The signature is  `reducer = reducer.mean.exclude-nulls( )`.

**Comment by hbs** [comment]
You are right, those signatures are auto generated, we should treat some
cases in a special way.
